<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Duck</AssemblyName>
        <RootNamespace>Duck</RootNamespace>
        <LangVersion>latestmajor</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0"/>
        <PackageReference Include="Silk.NET.Maths" Version="2.23.0"/>
        <PackageReference Include="ThomasLevesque.WeakEvent" Version="4.1.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\External\Arch.Extended\Arch.System\Arch.System.csproj"/>
        <ProjectReference Include="..\..\External\Arch\src\Arch\Arch.csproj"/>
        <ProjectReference Include="..\Serialization\Serialization.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\External\Arch.Extended\Arch.System.SourceGenerator\Arch.System.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\SerializationGenerators\SerializationGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

</Project>
