<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Duck.RenderSystem.Godot</AssemblyName>
        <RootNamespace>Duck.RenderSystem.Godot</RootNamespace>
        <LangVersion>latestmajor</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Engine\Engine.csproj"/>
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'debug' AND '$(OS)' == 'Unix'">
        <ContentWithTargetPath Include="$(SolutionDir)Build\libgodot.linuxbsd.editor.dev.x86_64.shared_library.so">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <TargetPath>libgodot.linuxbsd.editor.dev.x86_64.shared_library.so</TargetPath>
        </ContentWithTargetPath>
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'debug'">
        <Reference Include="GodotSharp" Private="true">
            <HintPath>$(SolutionDir)Build\GodotSharp\Api\Debug\GodotSharp.dll</HintPath>
        </Reference>
        <Reference Include="GodotSharpEditor" Private="true">
            <HintPath>$(SolutionDir)Build\GodotSharp\Api\Debug\GodotSharpEditor.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <None Include="$(SolutionDir)Build\GodotSharp\**" CopyToOutputDirectory="PreserveNewest" LinkBase="GodotSharp"/>
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\SerializationGenerators\SerializationGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\..\External\Arch.Extended\Arch.System.SourceGenerator\Arch.System.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>
</Project>
