<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AssemblyName>Duck.RenderSystem.Vulkan</AssemblyName>
        <RootNamespace>Duck.RenderSystem.Vulkan</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Engine\Engine.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Silk.NET.Vulkan" Version="2.23.0" />
        <PackageReference Include="Silk.NET.Vulkan.Extensions.EXT" Version="2.23.0" />
        <PackageReference Include="Silk.NET.Vulkan.Extensions.KHR" Version="2.23.0" />
        <PackageReference Include="Silk.NET.Windowing.Glfw" Version="2.23.0" />
        <PackageReference Include="Silk.NET.Windowing.Sdl" Version="2.23.0" />
    </ItemGroup>

</Project>
